title:              Amund Midtgard Raniseth
email:              amund.raniseth@gmail.com
description:        A project website aiming to document other personal projects.
author:             Amund Midtgard Raniseth
baseurl:            ""
url:                ""

# Social Profiles
#twitter_username:   SBootstrap
github_username:    amundmr
#facebook_username:  StartBootstrap
#instagram_username:  
linkedin_username: amund-midtgard-raniseth-9a551519a

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
