/** * RADIOAMATØR SPØRSMÅLSDATABASE (100+ Spørsmål)
 * Dekker Teknikk, Regelverk, Prosedyrer og Antenner.
 */
const questionBank = {
    teknikk: [
        { q: "Hva er enheten for kapasitans?", a: ["Farad", "Henry", "Ohm", "Watt"], c: 0 },
        { q: "Hva skjer med motstanden hvis du kobler to like motstander i parallell?", a: ["Den dobles", "Den blir uforandret", "Den halveres", "Den blir null"], c: 2 },
        { q: "Hva er frekvensen til en bølge med 2 meter bølgelengde?", a: ["145 MHz", "7 MHz", "3.5 MHz", "433 MHz"], c: 0 },
        { q: "Hvilken komponent brukes for å slippe strøm igjennom i bare én retning?", a: ["Resistor", "Diode", "Kondensator", "Spole"], c: 1 },
        { q: "Hva måles med et amperemeter?", a: ["Spenning", "Effekt", "Strømstyrke", "Frekvens"], c: 2 },
        { q: "Hva er formelen for effekt (P)?", a: ["P = U * I", "P = U / I", "P = R * I", "P = U + I"], c: 0 },
        { q: "Hva er enheten for induktans?", a: ["Farad", "Henry", "Siemens", "Tesla"], c: 1 },
        { q: "Hvilken type modulasjon endrer amplituden til bærebølgen?", a: ["FM", "AM", "PM", "CW"], c: 1 },
        { q: "Hva er fordelen med SSB (Single Sideband) fremfor AM?", a: ["Bedre lydkvalitet", "Mindre båndbredde og høyere effektivitet", "Trenger ingen antenne", "Det er lettere å stille inn"], c: 1 },
        { q: "Hva kalles kretsen som omformer vekselstrøm til likestrøm?", a: ["Oscillator", "Likretter", "Modulator", "Forsterker"], c: 1 },
        { q: "Hva er frekvensområdet for VHF?", a: ["3 - 30 MHz", "30 - 300 MHz", "300 - 3000 MHz", "30 - 300 kHz"], c: 1 },
        { q: "Hvis spenningen er 12V og motstanden er 4 Ohm, hva er strømmen?", a: ["48A", "3A", "0.33A", "8A"], c: 1 },
        { q: "Hva er båndbredden til et normalt SSB-signal?", a: ["500 Hz", "2.4 - 3 kHz", "6 kHz", "25 kHz"], c: 1 },
        { q: "Hvilken komponent lagrer energi i et magnetfelt?", a: ["Kondensator", "Spole", "Motstand", "Transistor"], c: 1 },
        { q: "Hva står forkortelsen 'AC' for?", a: ["Active Current", "Alternating Current", "Amperage Capacity", "Aerial Connection"], c: 1 },
        { q: "Hva er en transistor hovedsakelig brukt til?", a: ["Filtrering", "Forsterkning og svitsjing", "Lagring av strøm", "Generere varme"], c: 1 },
        { q: "Hva er 'PEP' forkortelse for?", a: ["Peak Envelope Power", "Primary Electrical Potential", "Pulse Energy Period", "Power Efficiency Peak"], c: 0 },
        { q: "Hva skjer i en mikser-krets?", a: ["To signaler legges sammen lineært", "To signaler multipliseres for å lage nye frekvenser", "Signalet blir bare forsterket", "Støy blir fjernet"], c: 1 },
        { q: "Hva er frekvensen til en bølge på 70cm?", a: ["145 MHz", "433 MHz", "1.2 GHz", "28 MHz"], c: 1 },
        { q: "Hva er enheten for elektrisk ladning?", a: ["Volt", "Coulomb", "Ampere", "Joule"], c: 1 },
        { q: "Hva er resonansfrekvens?", a: ["Den laveste frekvensen en radio kan motta", "Frekvensen der induktiv og kapasitiv reaktans utligner hverandre", "Når radioen blir varm", "Når lyden er på det høyeste"], c: 1 },
        { q: "Hvilket filter slipper igjennom lave frekvenser, men stopper høye?", a: ["Høypassfilter", "Lavpassfilter", "Båndpassfilter", "Båndstoppfilter"], c: 1 },
        { q: "Hva er en zener-diode ofte brukt til?", a: ["Lysutslipp", "Spenningsstabilisering", "Høyfrekvent svitsjing", "Temperaturmåling"], c: 1 },
        { q: "Hva måles impedans i?", a: ["Henry", "Ohm", "Farad", "Watt"], c: 1 },
        { q: "Hva er en 'VFO'?", a: ["Variable Frequency Oscillator", "Very Fast Operation", "Vertical Frequency Output", "Voltage Filter Operator"], c: 0 },
        { q: "Hvor mange hertz er 14.250 MHz?", a: ["14 250 Hz", "142 500 Hz", "14 250 000 Hz", "1 425 000 Hz"], c: 2 },
        { q: "Hvilken bølgeform har renest frekvensinnhold?", a: ["Firkantbølge", "Sagtannbølge", "Sinusbølge", "Pulsbølge"], c: 2 },
        { q: "Hva kalles forholdet mellom utgangseffekt og inngangseffekt?", a: ["Resonans", "Forsterkning (Gain)", "Demping", "Modulasjonsgrad"], c: 1 },
        { q: "Hva skjer med kapasitansen hvis platearealet i en kondensator økes?", a: ["Den minker", "Den øker", "Den forblir lik", "Den blir null"], c: 1 },
        { q: "Hva er hensikten med en 'Squelch'-kontroll?", a: ["Å øke volumet", "Å fjerne bakgrunnsstøy når det ikke er signal", "Å fininnstille frekvensen", "Å endre båndbredden"], c: 1 }
    ],
    regelverk: [
        { q: "Hva er prefikset for norske radioamatører?", a: ["LA", "LB", "LG", "Alle de nevnte"], c: 3 },
        { q: "Hvor ofte skal man identifisere seg med kallesignal?", a: ["Hvert minutt", "Ved begynnelse, slutt og minst hvert 10. minutt", "Bare når man avslutter", "Hver time"], c: 1 },
        { q: "Hvilken aldersgrense er det for å få radioamatørlisens i Norge?", a: ["12 år", "16 år", "18 år", "Ingen nedre aldersgrense"], c: 3 },
        { q: "Hva er formålet med radioamatørtjenesten?", a: ["Kommersiell kringkasting", "Egentrening, kommunikasjon og tekniske undersøkelser", "Taxi-virksomhet", "Privat underholdning"], c: 1 },
        { q: "Hvem tildeler kallesignal i Norge?", a: ["NRRL", "Nasjonal kommunikasjonsmyndighet (Nkom)", "Politiet", "Telenor"], c: 1 },
        { q: "Hvilket frekvensbånd kalles '20-meteren'?", a: ["7.0 - 7.2 MHz", "14.0 - 14.35 MHz", "21.0 - 21.45 MHz", "3.5 - 3.8 MHz"], c: 1 },
        { q: "Hva betyr 'CEPT-anbefaling T/R 61-01'?", a: ["At du kan bruke radioen din i andre CEPT-land uten ekstra søknad", "At du må betale skatt på radioen", "At du bare kan sende på VHF", "At digital radio er forbudt"], c: 0 },
        { q: "Er det lov å sende musikk over amatørradio?", a: ["Ja, hvis det er god musikk", "Nei, aldri", "Ja, på lørdager", "Bare på korte tester"], c: 1 },
        { q: "Hva er maksimal tillatt effekt for en norsk radioamatør (normalt)?", a: ["100W", "1000W", "25W", "500W"], c: 1 },
        { q: "Har radioamatører lov til å formidle meldinger for tredjepart?", a: ["Ja, mot betaling", "Normalt ikke, unntatt i nødssituasjoner", "Ja, alltid", "Bare til familiemedlemmer"], c: 1 },
        { q: "Hvilket dokument må du ha med når du bruker radio i utlandet?", a: ["Passet ditt", "HAREC-sertifikat og lisens", "Førerkort", "Kvittering på radioen"], c: 1 },
        { q: "Hvilken organisasjon representerer norske radioamatører internasjonalt?", a: ["Nkom", "NRRL (tilsluttet IARU)", "ITU", "FN"], c: 1 },
        { q: "Hva er 'IARU'?", a: ["En type antenne", "International Amateur Radio Union", "En nødprosedyre", "Et digitalt kallesignal"], c: 1 },
        { q: "Hva betyr 'primær bruker' i båndplanen?", a: ["Brukeren har førsterett og skal ikke forstyrres", "Brukeren er den første som bygde radioen", "At man bare kan sende på dagtid", "Ingenting spesielt"], c: 0 },
        { q: "Hva er kravet til teknisk utførelse av amatørradiostasjonen?", a: ["Den må være fabrikkbygd", "Den skal ikke forårsake unødig forstyrrelse for andre", "Den må være grønn", "Den må ha digital skjerm"], c: 1 },
        { q: "Hva er frekvensområdet for 80-meter båndet?", a: ["1.8 - 2.0 MHz", "3.5 - 3.8 MHz", "7.0 - 7.2 MHz", "28 - 29.7 MHz"], c: 1 },
        { q: "Hvilket kallesignal-prefiks brukes på Svalbard?", a: ["LA", "JW", "JX", "3Y"], c: 1 },
        { q: "Hva er kravet for å kalle seg radioamatør?", a: ["At du har kjøpt en radio", "At du har bestått prøve og har gyldig lisens", "At du kan morse", "At du er over 18 år"], c: 1 },
        { q: "Hvem har ansvaret for at stasjonen ikke sender utstyr utenfor amatørbåndene?", a: ["Nkom", "NRRL", "Lisensinnehaveren", "Produsenten av radioen"], c: 2 },
        { q: "Kan du bruke amatørradio til kommersiell virksomhet?", a: ["Ja", "Nei", "Bare på søndager", "Bare hvis du betaler ekstra skatt"], c: 1 },
        { q: "Hva betyr 'QRM'?", a: ["Jeg har støy fra atmosfæren", "Jeg blir forstyrret av andre stasjoner", "Jeg flytter frekvens", "Været er dårlig"], c: 1 },
        { q: "Hva er kravet for kallesignal ved bruk av bærbar stasjon (portable)?", a: ["Legg til /P etter kallesignalet", "Legg til /M etter kallesignalet", "Bruk et helt nytt navn", "Ingen endring nødvendig"], c: 0 },
        { q: "Hva er 'IARU Region 1'?", a: ["Nord- og Sør-Amerika", "Europa, Afrika og Nord-Asia", "Oseania", "Sør-Asia"], c: 1 },
        { q: "Hva er lovlig bruk av amatørradio i nødssituasjoner?", a: ["Bruke alle tilgjengelige midler for å få kontakt", "Bare bruke 145.500 MHz", "Vente på tillatelse fra politiet", "Bare sende i morse"], c: 0 },
        { q: "Hvor lang er gyldigheten til en norsk radioamatørlisens?", a: ["5 år", "10 år", "Livsvarig (inntil den blir slettet/sagt opp)", "1 år"], c: 2 }
    ],
    prosedyrer: [
        { q: "Hva betyr 'QRL'?", a: ["Er frekvensen opptatt?", "Hva er din posisjon?", "Jeg kaller alle", "Slutt på sending"], c: 0 },
        { q: "Hvilket ord brukes i det fonetiske alfabetet for bokstaven 'H'?", a: ["Holland", "Hotel", "Happy", "Henry"], c: 1 },
        { q: "Hva betyr meldingen 'Mayday'?", a: ["Jeg ønsker en test", "Jeg har tekniske problemer", "Nødmelding - liv og helse i fare", "God morgen"], c: 2 },
        { q: "Hva betyr '73' i amatørradio-sjargong?", a: ["Hade bra / Beste hilsener", "Jeg er sint", "Været er fint", "Gjenta meldingen"], c: 0 },
        { q: "Hva betyr Q-koden 'QRS'?", a: ["Send saktere", "Øk effekten", "Stopp sending", "Hvem kaller?"], c: 0 },
        { q: "Hva står RST-systemet for?", a: ["Radio, Static, Tone", "Readability, Strength, Tone", "Range, Signal, Time", "Readability, Signal, Tension"], c: 1 },
        { q: "Hva er den internasjonale kallefrekvensen på VHF (FM)?", a: ["144.800 MHz", "145.500 MHz", "145.200 MHz", "144.300 MHz"], c: 1 },
        { q: "Hvordan staver du 'RADIO' med det fonetiske alfabetet?", a: ["Robert Alpha David Isaac Oscar", "Romeo Alpha Delta India Oscar", "Romeo Alpha Delta Ice Omega", "Radio Alpha Delta India Oscar"], c: 1 },
        { q: "Hva betyr 'CQ'?", a: ["Søk kontakt (jeg kaller alle)", "Slutt på sending", "Klar for mottak", "Hva er din posisjon?"], c: 0 },
        { q: "Hva er 'QSL-kort'?", a: ["Et medlemskort i NRRL", "Et kort som bekrefter en radiokontakt", "Et kredittkort for radioutstyr", "En tillatelse til å sende"], c: 1 },
        { q: "Hva betyr 'QTH'?", a: ["Min posisjon (sted) er...", "Jeg har forstyrrelser", "Vennligst vent", "Hvem kaller meg?"], c: 0 },
        { q: "Hva er korrekt prosedyre for å starte et kalleopprop?", a: ["Navnet ditt to ganger", "CQ CQ CQ de [Ditt Kallesignal]", "Bare kallesignalet ditt", "Hei, er det noen der?"], c: 1 },
        { q: "Hva betyr 'QSB'?", a: ["Signalet ditt fader (styrken varierer)", "Jeg er opptatt", "Flytt frekvens", "Jeg mottar deg dårlig"], c: 0 },
        { q: "Hva betyr 'QRM'?", a: ["Atmosfærisk støy", "Menneskeskapt støy / interferens fra andre", "Slutt på sending", "Jeg er klar"], c: 1 },
        { q: "Hva betyr 'QRZ'?", a: ["Hvem kaller meg?", "Gå til en annen frekvens", "Stopp sending", "Signalet er sterkt"], c: 0 },
        { q: "Hvilken bokstav i det fonetiske alfabetet er 'X'?", a: ["X-ray", "Xylophone", "Xenon", "X-factor"], c: 0 },
        { q: "Hva betyr 'Break-in' i CW-sammenheng?", a: ["At man kan høre motstasjonen mellom egne tegn", "At man bryter seg inn i en samtale", "At radioen er ødelagt", "At man sender veldig fort"], c: 0 },
        { q: "Hva betyr 'Tailending'?", a: ["Å avslutte en samtale raskt", "Å kalle en stasjon rett etter at de har avsluttet med en annen", "Å bruke en lang antenne", "Å sende bakerst i båndet"], c: 1 },
        { q: "Hvilken frekvens brukes til digital APRS i Europa på VHF?", a: ["144.800 MHz", "145.500 MHz", "144.000 MHz", "146.000 MHz"], c: 0 },
        { q: "Hva betyr 'DX'?", a: ["Kortdistanse", "Langdistanse (ofte andre kontinenter)", "Digital overføring", "Dobbelt signal"], c: 1 },
        { q: "Hva betyr 'Roger' i tale-kommunikasjon?", a: ["Jeg har mottatt og forstått meldingen din", "Mitt navn er Roger", "Slutt på sending", "Vennligst gjenta"], c: 0 },
        { q: "Hva er 'UTC'?", a: ["Universal Time Coordinated (verdenstid)", "Under The Clouds", "Ultra Tension Control", "United Transmission Code"], c: 0 },
        { q: "Hva betyr 'Fine Business' (FB)?", a: ["At man selger utstyr", "At alt fungerer bra / flott", "At man er profesjonell", "At man har en bedrift"], c: 1 },
        { q: "Hva betyr 'Over'?", a: ["Jeg er ferdig med å snakke og venter på ditt svar", "Samtalen er helt ferdig", "Jeg flytter frekvens", "Signalet er for sterkt"], c: 0 },
        { q: "Hva betyr 'Out'?", a: ["Jeg går ut en tur", "Jeg avslutter kontakten helt", "Jeg venter på svar", "Radioen er skrudd av"], c: 1 }
    ],
    antenner: [
        { q: "Hvilken lengde har normalt en dipol-antenne?", a: ["1 bølgelengde", "1/2 bølgelengde", "1/4 bølgelengde", "5/8 bølgelengde"], c: 1 },
        { q: "Hva skjer hvis SWR er for høyt?", a: ["Radioen kan bli skadet av reflektert effekt", "Signalet når lengre", "Lyden blir klarere", "Batteriet varer lenger"], c: 0 },
        { q: "Hva er en 'Yagi'?", a: ["En type batteri", "En retningsstyrt antenne", "En digital modulasjon", "Et kallesignal fra Japan"], c: 1 },
        { q: "Hva er polarisasjonen til en vertikal piskantenne?", a: ["Horisontal", "Vertikal", "Sirkulær", "Ingen"], c: 1 },
        { q: "Hvilket lag i atmosfæren reflekterer kortbølgesignaler tilbake til jorden?", a: ["Troposfæren", "Ionosfæren", "Stratosfæren", "Mesosfæren"], c: 1 },
        { q: "Hva er en 'Dummy Load'?", a: ["En tung radio", "En kunstig antenne som ikke stråler, brukt til testing", "En uerfaren radiooperatør", "En reserve-antenne"], c: 1 },
        { q: "Hva er fordelen med en retningsantenne (beam)?", a: ["Den er mindre", "Den forsterker signalet i en bestemt retning", "Den tar imot støy fra alle kanter", "Den trenger ikke kabel"], c: 1 },
        { q: "Hva står SWR for?", a: ["Signal Wave Rate", "Standing Wave Ratio", "Static Wave Resistance", "Standard Wireless Range"], c: 1 },
        { q: "Hva er en koaksialkabel?", a: ["En kabel med to parallelle ledere", "En kabel med en senterleder og en skjerm", "En strømkabel", "En fiberoptisk kabel"], c: 1 },
        { q: "Hva er 'Gain' i en antenne?", a: ["Hvor mye den veier", "Evnen til å fokusere energi i en retning sammenlignet med en referanse", "Prisen på antennen", "Hvor mange bånd den dekker"], c: 1 },
        { q: "Hva skjer med signalet i 'Skip'-sonen (dødsone)?", a: ["Det er på sitt sterkeste", "Signalet hopper over dette området via ionosfæren", "Signalet forsvinner helt fra jordens overflate", "Det blir omgjort til støy"], c: 1 },
        { q: "Hva er en 'Ground Plane'-antenne?", a: ["En antenne som ligger på bakken", "En vertikal antenne med radialer som fungerer som motvekt", "En antenne brukt i fly", "En horisontal dipol"], c: 1 },
        { q: "Hva er karakteristisk impedans for en standard koaksialkabel til radio?", a: ["50 Ohm", "75 Ohm", "300 Ohm", "8 Ohm"], c: 0 },
        { q: "Hva er en 'Balun'?", a: ["Et kallenavn på en antenne", "En transformator mellom balansert og ubalansert last", "En type batteri", "En vindmåler"], c: 1 },
        { q: "Hva påvirker de høyeste frekvensene ionosfæren kan reflektere?", a: ["Månefasene", "Solaktivitet (solflekker)", "Tidevannet", "Vindstyrken"], c: 1 },
        { q: "Hvilken antenne er rundstrålende i det horisontale planet?", a: ["Yagi", "Vertikal piskantenne", "Parabol", "Kvadrantantenne"], c: 1 },
        { q: "Hva er 'Velocity Factor' i en kabel?", a: ["Hvor fort man kan rulle den opp", "Hvor mye saktere bølgen går i kabelen enn i vakuum", "Hvor mye strøm den tåler", "Vekten per meter"], c: 1 },
        { q: "Hvorfor bør man unngå høyt SWR?", a: ["Det kan ødelegge utgangstransistorene i radioen", "Det gjør at man sender på feil frekvens", "Det lager for mye lyd i høyttaleren", "Det er ulovlig"], c: 0 },
        { q: "Hva er en 'Log-periodisk antenne'?", a: ["En antenne som bare virker av og til", "En bredbåndsantenne som dekker mange frekvenser", "En antenne som måler tid", "En digital antenne"], c: 1 },
        { q: "Hva er den teoretiske impedansen i senter av en halvbølge-dipol i fritt rom?", a: ["50 Ohm", "73 Ohm", "300 Ohm", "10 Ohm"], c: 1 },
        { q: "Hva er hensikten med 'radialer'?", a: ["Å pynte på antennen", "Å skape et kunstig jordplan for en vertikalantenne", "Å fange opp mer regnvann", "Å øke vekten"], c: 1 },
        { q: "Hva er 'E-skip' (Sporadic E)?", a: ["En feil i radioen", "Uvanlig refleksjon i E-laget som gir langdistanse på VHF", "En type digital koding", "En rask måte å sende morse på"], c: 1 },
        { q: "Hva er polarisasjonen til en dipol som henger parallelt med bakken?", a: ["Vertikal", "Horisontal", "Sirkulær", "Ingen"], c: 1 },
        { q: "Hvilken kabel har minst tap på høye frekvenser?", a: ["Tynn koaksialkabel (RG-58)", "Tykk koaksialkabel med lavt tap", "Lampeledning", "Telefonkabel"], c: 1 },
        { q: "Hva er 'SWR-meter'?", a: ["Et apparat som måler hvor mye effekt som sendes vs. reflekteres", "Et apparat som måler lydstyrke", "En frekvensteller", "En klokke"], c: 0 }
    ]
};